//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZamaraESS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://afken1bcuatapp1.zamara.co.ke:7047/UAT/WS/ZAAC/Codeunit/finservice")]
        public string ZamaraESS_FinService_finservice {
            get {
                return ((string)(this["ZamaraESS_FinService_finservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://afken1bcuatapp1.zamara.co.ke:7047/UAT/WS/ZAAC/Codeunit/procservice")]
        public string ZamaraESS_ProcService_procservice {
            get {
                return ((string)(this["ZamaraESS_ProcService_procservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://afken1bcuatapp1.zamara.co.ke:7047/UAT/WS/ZAAC/Codeunit/hrservice")]
        public string ZamaraESS_HrService_hrservice {
            get {
                return ((string)(this["ZamaraESS_HrService_hrservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://afken1bcprodapp1.zamara.co.ke:7107/ZamaraHF/WS/ZARIB/Codeunit/procservice")]
        public string ZamaraESS_ProcServiceZarib_procservice {
            get {
                return ((string)(this["ZamaraESS_ProcServiceZarib_procservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://afken1bcprodapp1.zamara.co.ke:7107/ZamaraHF/WS/ZARIB/Codeunit/finservice")]
        public string ZamaraESS_FinServiceZarib_finservice {
            get {
                return ((string)(this["ZamaraESS_FinServiceZarib_finservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://afken1bcprodapp1.zamara.co.ke:7107/ZamaraHF/WS/ZARIB/Codeunit/hrservice")]
        public string ZamaraESS_HrServiceZarib_hrservice {
            get {
                return ((string)(this["ZamaraESS_HrServiceZarib_hrservice"]));
            }
        }
    }
}
